language: python

python:
  # - "2.7"
  # - "3.5"
  - "3.7"

install:
  - pip install -r requirements.txt
  # - virtualenv .venv
  # - source .venv/bin/activate
  # - pip install -r requirements.txt
# command to run tests
script:
  # unit test
  - python -m pytest -v
# # linting test
# - flake
