DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS rating;

CREATE TABLE user (
  userID INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE rating (
  ratingID INTEGER PRIMARY KEY AUTOINCREMENT,
  userID INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ratingVal INTEGER NOT NULL,
  FOREIGN KEY (userID) REFERENCES user (userID)
);